# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

registries:
  nuget-dotnet-reproducible-builds:
    type: nuget-feed
    url: https://pkgs.dev.azure.com/dotnet/Projects/_packaging/ReproducibleBuilds/nuget/v3/index.json

updates:
  - package-ecosystem: nuget
    directory: '/'
    registries:
      - nuget-dotnet-reproducible-builds
    allow:
      - dependency-name: DotNet.ReproducibleBuilds
      - dependency-name: DotNet.ReproducibleBuilds.Isolated
    schedule:
      interval: weekly

  - package-ecosystem: nuget
    directory: '/'
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: '/.github'
    schedule:
      interval: weekly
